[package]
name = "base58-turbo"
version = "0.3.0"
rust-version = "1.87"
edition = "2024"
readme = "README.md"
authors = ["Hacer-Bark <hacer.bark@proton.me>"]
license = "0BSD"
description = "A Rust Base58 codec that decodes past 1.5 GiB/s, 100% safe Rust."
repository = "https://github.com/hacer-bark/base58-turbo"
documentation = "https://docs.rs/base58-turbo"
keywords = ["base58", "encoding", "decoding", "performance", "crypto"]
categories = ["encoding", "cryptography", "no-std"]
exclude = ["benches/scripts/", "benches/results/"]

[features]
default = ["std"]
std = []

[dev-dependencies]
rand = "0.10"
criterion = { version = "0.8", features = ["html_reports"] }
bs58 = "0.5"
base58 = "0.2"
five8 = "1"
base58-monero = "2"

[lints.rust]
warnings = "deny"
future_incompatible = { level = "deny", priority = -1 }
unused = { level = "deny", priority = -1 }
missing_docs = "deny"
missing_debug_implementations = "deny"
unreachable_pub = "deny"
unsafe_code = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }

[lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"

[lints.rustdoc]
all = "deny"
broken_intra_doc_links = "deny"

[[bench]]
name = "encoding_bench"
harness = false
